pipeline
{
    agent any
    
        stages
        {
            stage('build')
            {
                steps
                {
                    bat 'mvn -f htmldemo/pom.xml clean install'
                }
                post
                {
                    success
                    {
                        echo 'now archaiving............'
                        archiveArtifacts artifacts : '**/*.war'
                    }
                }
            }
        }
    
}